site_name: Using the Pet Clinic Sample Application
pages: 
  - Introduction: index.md
  - Deploying the Pet Clinic Application: deployment.md
theme: readthedocs
markdown_extensions: [ codehilite, smarty ]
extra_css: [ css/extra.css ]