site_name: Using the Pet Clinic Sample Application
pages: 
  - Introduction: index.md
  - Deploying the Pet Clinic Application: deploying-petclinic.md
  - Notes: notes.md
theme: readthedocs
markdown_extensions: [ codehilite ]
extra_css: [ css/extra.css ]